<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IGL70596" failures="0" tests="2" name="Testscript.NMTS" time="241.917" errors="1" timestamp="18 Nov 2019 08:45:34 GMT">
  <testcase classname="Testscript.NMTS" name="NumberInquiryForNMTS" time="54.628">
    <error message=" &lt;font color=&#039;red&#039;&gt; Either data is incorrect in excel sheet or no Record found in system Application &lt;/font&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  <font color='red'> Either data is incorrect in excel sheet or no Record found in system Application </font>
	at org.testng.Assert.fail(Assert.java:94)
	at Driver.DriverHelper.RedLog(DriverHelper.java:1126)
	at ScriptHelper.NmtsHelper.ReservetoActivateScenario(NmtsHelper.java:1215)
	at ScriptHelper.NmtsHelper.SearchofNMTSScenario(NmtsHelper.java:98)
	at Testscript.NMTS.NumberInquiryForNMTS(NMTS.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- NumberInquiryForNMTS -->
  <testcase classname="Testscript.NMTS" name="NumberInquiryForNMTS" time="187.289"/>
</testsuite> <!-- Testscript.NMTS -->
